# [Template] Codesign using config.

parameters:
  ConfigName: ""

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: "${{ parameters.ConfigName }}"
- task: PkgESCodeSign@10
  inputs:
    signConfigXml: $(Agent.TempDirectory)\${{ parameters.ConfigName }}
    inPathRoot: $(Build.SourcesDirectory)
    outPathRoot: $(Build.SourcesDirectory)  
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)